In [1]:
import pandas as pd

pd.__version__

'2.2.3'

In [4]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")

In [5]:
len(df)

10000

In [8]:
df.head(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [10]:
df["fuel_type"].value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

In [11]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

What's the maximum fuel efficiency of cars from Asia?

In [12]:
df.groupby('origin').fuel_efficiency_mpg.max()

origin
Asia      41.2
Europe    39.4
USA       38.2
Name: fuel_efficiency_mpg, dtype: float64

In [13]:
df["horsepower"].median()

254.0

In [14]:
df["horsepower"].mode()

0    252.0
Name: horsepower, dtype: float64

In [15]:
df["horsepower"].isnull().sum()

877

In [18]:
df["horsepower"] = df["horsepower"].fillna(df["horsepower"].mode()[0])

In [19]:
df["horsepower"].isnull().sum()

0

In [20]:
df["horsepower"].median()

252.0

In [22]:
df_asia = df[df["origin"] == "Asia"]
df_asia.head(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [23]:
col = df_asia[["vehicle_weight", "model_year"]]
col = col.head(7)
col

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [24]:
import numpy as np
X = col.to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [26]:
XT = X.T
XT

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [27]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result
def matrix_matrix_multiplication(U, V):

    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [29]:
XTX= matrix_matrix_multiplication(XT, X)
XTX

array([[1.3195050e+08, 6.0750580e+07],
       [6.0750580e+07, 2.8041424e+07]])

In [32]:
XTX_inv = np.linalg.inv(XTX)

In [30]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [34]:
w = (XTX_inv @  XT) @  y

In [35]:
w.sum()

0.3691969690492758